spring:
  application:
    name: AWS_S3_SVC
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/aws_db?useSSL=false
    username: postgres
    password: 1234

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8082

cloud:
  aws:
    credentials:
      access-key: AKIA3OJQYSVUAPRQ3WV3
      secret-key: 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
    region:
      static: eu-north-1

aws:
  bucket:
    name: nexio-aws-s3
    folder:
      profile-pic: profile-pictures/
      item-pic: item-pictures/

